import re

patterns = [
        ["1_android_access_mode-world-readable", "MODE_WORLD_READABLE"],
        ["1_android_access_mode-world-writeable", "MODE_WORLD_WRITEABLE"],
        ["1_android_ssl_hostname_verifier", "ALLOW_ALL_HOSTNAME_VERIFIER"],
        ["1_android_setWebContentsDebuggingEnabled", "\.setWebContentsDebuggingEnabled\("],
        ["2_android_dexguar_TamperDetector", "TamperDetector"],
        ["2_android_dexguar_CertificateChecker", "CertificateChecker"],
        ["2_android_intents_intent-filter_registerReceiver", "registerReceiver\("],
        ["2_android_webview_setAllowUniversalAccessFromFileURLs", "setAllowUniversalAccessFromFileURLs"],
        ["2_android_webview_setAllowFileAccess", "setAllowFileAccess"],
        ["2_android_SafetyNet", "SafetyNet"],
        ["2_android_AttestationResult", "AttestationResult"],
        ["3_android_access_mode-private", "MODE_PRIVATE"],
        ["3_android_access_rawQuery", "rawQuery\("],
        ["3_android_access_rawQueryWithFactory", "rawQueryWithFactory\("],
        ["3_android_access_compileStatement", "compileStatement\("],
        ["3_android_intents_intent-filter_exported", "android:exported.{0,$WILDCARD_SHORT}true"],
        ["3_android_intents_intent-filter_sendBroadcast", "sendBroadcast\("],
        ["3_android_ssl_x509TrustManager", "X509TrustManager"],
        ["3_android_ssl_trustStrategy", "implements TrustStrategy"],
        ["3_android_setUserAuthenticationValidityDurationSeconds", "setUserAuthenticationValidityDurationSeconds"],
        ["3_android_contentResolver", "ContentResolver"],
        ["3_android_webview_setAllow", "\.setAllow\("],
        ["3_android_system_path", "/system"],
        ["3_android_superuser_apk", "Superuser.apk"],
        ["3_android_supersu", "supersu"],
        ["3_android_ro.secure", "ro\.secure"],
        ["3_android_isDebuggerConnected", "isDebuggerConnected"],
        ["4_android_intents_startActivity", "startActivity\("],
        ["4_android_intents_getIntent", "\.getIntent\("],
        ["4_android_intents_getData", "\.getData\("],
        ["4_android_uri_parse", "Uri.parse\("],
        ["4_android_intents_setData", "\.setData\("],
        ["4_android_intents_RunningAppProcessInfo", "RunningAppProcessInfo"],
        ["4_android_AndroidKeyStore", "AndroidKeyStore"],
        ["4_android_webview_loadData", "\.loadData\("],
        ["4_android_webview_loadUrl", "\.loadUrl\("],
        ["4_android_backupAgent", "BackupAgent"],
        ["5_android_access_openFile", "\.openFile\("],
        ["5_android_access_openAssetFile", "\.openAssetFile\("],
        ["5_android_access_openOrCreate", "\.openOrCreate"],
        ["5_android_access_getDatabase", "\.getDatabase\("],
        ["5_android_access_openDatabase", "\.openDatabase\("],
        ["5_android_access_getShared", "\.getShared"],
        ["5_android_access_getCache", "\.getCache"],
        ["5_android_access_getCodeCache", "\.getCodeCache"],
        ["5_android_access_getExternalCache", "\.getExternalCache"],
        ["5_android_access_getExternalFile", "\.getExternalFile"],
        ["5_android_access_getExternalMedia", "\.getExternalMedia"],
        ["5_android_access_query", "query\("],
        ["5_android_keyStorage", "KeyStore"],
        ["5_android_FLAG_ACTIVITY_NEW_TASK", "FLAG_ACTIVITY_NEW_TASK"],
        ["6_android_logging_error", "Log\.e\("],
        ["6_android_logging_warning", "Log\.w\("],
        ["6_android_logging_information", "Log\.i\("],
        ["6_android_logging_debug", "Log\.d\("],
        ["6_android_logging_verbose", "Log\.v\("],
        ["3_angularjs_sceprovider_enabled", "sceProvider\.enabled\("],

        ["2_c_insecure_c_functions_memcpy", "memcpy\("],
        ["2_c_insecure_c_functions_memset", "memset\("],
        ["2_c_insecure_c_functions_strcat_strncat", "strn?cat\("],
        ["2_c_insecure_c_functions_strcpy_strncpy", "strn?cpy\("],
        ["2_c_insecure_c_functions_sprintf_snprintf", "sn?printf\("],
        ["2_c_insecure_c_functions_fprintf_fnprintf", "fn?printf\("],
        ["2_c_insecure_c_functions_fscanf_scanf", "f?scanf\("],
        ["2_c_insecure_c_functions_gets", "gets\("],
        ["2_c_random", "random\("],
        ["4_c_malloc", "malloc\("],
        ["4_c_realloc", "realloc\("],

        ["1_cryptocred_certificates_and_keys_narrow_private-key", "PRIVATE KEY", re.IGNORECASE],
        ["1_cryptocred_net_user_add", "net user.{0,$WILDCARD_LONG}/add", re.IGNORECASE],
        ["2_cryptocred_encryption_key", "encrypt.{0,$WILDCARD_SHORT}key", re.IGNORECASE],
        ["2_cryptocred_dev_random", "/dev/u?random"],
        ["2_cryptocred_certificates_and_keys_narrow_begin-certificate", "BEGIN CERTIFICATE", re.IGNORECASE],
        ["2_cryptocred_certificates_and_keys_narrow_public-key", "PUBLIC KEY", re.IGNORECASE],
        ["2_cryptocred_default_password", "default.?password", re.IGNORECASE],
        ["2_cryptocred_credentials_narrow", "creden.{0,$WILDCARD_SHORT}=.?[\"'\d]", re.IGNORECASE],
        ["2_cryptocred_passcode_narrow", "pass.?code.{0,$WILDCARD_SHORT}=.?[\"'\d]", re.IGNORECASE],
        ["2_cryptocred_passphrase_narrow", "pass.?phrase.{0,$WILDCARD_SHORT}=.?[\"'\d]", re.IGNORECASE],
        ["2_cryptocred_secret_narrow", "se?3?cre?3?t.{0,$WILDCARD_SHORT}=.?[\"'\d]", re.IGNORECASE],
        ["2_cryptocred_pin_code_narrow", "pin.?code.{0,$WILDCARD_SHORT}=.?[\"'\d]", re.IGNORECASE],
        ["3_cryptocred_crypt_call", "crypt\(", re.IGNORECASE],
        ["3_cryptocred_ciphers_rot32", "ROT32", re.IGNORECASE],
        ["3_cryptocred_ciphers_rc2", "RC2", re.IGNORECASE],
        ["3_cryptocred_ciphers_rc4", "RC4", re.IGNORECASE],
        ["3_cryptocred_ciphers_crc32", "CRC32", re.IGNORECASE],
        ["3_cryptocred_ciphers_des", "DES|TripleDES|.DES", re.IGNORECASE],
        ["3_cryptocred_ciphers_md2", "MD2", re.IGNORECASE],
        ["3_cryptocred_ciphers_md5", "MD5", re.IGNORECASE],
        ["3_cryptocred_ciphers_xor", "xor", re.IGNORECASE],
        ["3_cryptocred_ciphers_sha1_uppercase", "SHA-?1", re.IGNORECASE],
        ["3_cryptocred_ciphers_sha256", "SHA-?256", re.IGNORECASE],
        ["3_cryptocred_ciphers_sha512", "SHA-?512", re.IGNORECASE],
        ["3_cryptocred_ciphers_PBKDF2", "PBKDF2", re.IGNORECASE],
        ["3_cryptocred_ciphers_hmac", "HMAC", re.IGNORECASE],
        ["3_cryptocred_ciphers_ntlm", "NTLM", re.IGNORECASE],
        ["3_cryptocred_ciphers_kerberos", "kerberos", re.IGNORECASE],
        ["3_cryptocred_password", "pass.?wo?r?d", re.IGNORECASE],
        ["3_cryptocred_encoded_pw", "encoded.?pw", re.IGNORECASE],
        ["3_cryptocred_ssl_usage_require-ssl", "require.{0,$WILDCARD_SHORT}SSL", re.IGNORECASE],
        ["3_cryptocred_ssl_usage_use-ssl", "use.{0,$WILDCARD_SHORT}SSL", re.IGNORECASE],
        ["3_cryptocred_tls_usage_require-tls", "require.{0,$WILDCARD_SHORT}TLS", re.IGNORECASE],
        ["3_cryptocred_tls_usage_use-tls", "use.{0,$WILDCARD_SHORT}TLS", re.IGNORECASE],
        ["4_cryptocred_certificates_and_keys_wide_begin-certificate", "BEGIN.{0,$WILDCARD_SHORT}CERTIFICATE", re.IGNORECASE],
        ["4_cryptocred_certificates_and_keys_wide_private-key", "PRIVATE.{0,$WILDCARD_SHORT}KEY", re.IGNORECASE],
        ["4_cryptocred_certificates_and_keys_wide_public-key", "PUBLIC.{0,$WILDCARD_SHORT}KEY", re.IGNORECASE],
        ["4_cryptocred_pw_capitalcase", "PW.?=", re.IGNORECASE],
        ["4_cryptocred_pwd_uppercase", "PWD", re.IGNORECASE],
        ["4_cryptocred_pwd_lowercase", "pwd", re.IGNORECASE],
        ["4_cryptocred_pwd_capitalcase", "Pwd", re.IGNORECASE],
        ["4_cryptocred_credentials_wide", "creden", re.IGNORECASE],
        ["4_cryptocred_passcode_wide", "pass.?code", re.IGNORECASE],
        ["4_cryptocred_passphrase_wide", "pass.?phrase", re.IGNORECASE],
        ["4_cryptocred_secret_wide", "se?3?cre?3?t", re.IGNORECASE],
        ["4_cryptocred_pin_code_wide", "pin.?code", re.IGNORECASE],
        ["4_cryptocred_proxy-authorization", "Proxy.?Authoris?z?ation", re.IGNORECASE],
        ["4_cryptocred_authorization", "Authori[sz]ation", re.IGNORECASE],
        ["4_cryptocred_authentication", "Authentication", re.IGNORECASE],
        ["4_cryptocred_auth", "Auth", re.IGNORECASE],
        ["5_cryptocred_hash", "hash(?!(table|map|set|code))", re.IGNORECASE],
        ["5_cryptocred_salt1", "[Ss]alt", re.IGNORECASE],
        ["5_cryptocred_salt2", "SALT", re.IGNORECASE],
        ["5_cryptocred_hexdigest", "hex.?digest", re.IGNORECASE],

        ["1_dotnet_stringformat_sqli", "string\.Format\(.{0,$WILDCARD_SHORT}SELECT.{0,$WILDCARD_LONG}FROM", re.IGNORECASE],
        ["2_dotnet_validate_request", "ValidateRequest"],
        ["2_dotnet_unsafe_declaration", "unsafe\s", re.IGNORECASE],
        ["2_dotnet_marshal", "Marshal"],
        ["2_dotnet_LayoutKind_explicit", "LayoutKind\.Explicit"],
        ["2_dotnet_SuppressUnmanagedCodeSecurityAttribute", "SuppressUnmanagedCodeSecurityAttribute"],
        ["2_dotnet_DeserializationGarget", "BinaryFormatter|BinaryMessageFormatter|ObjectStateFormatter|LosFormatter|SoapFormatter|NetDataContractSerializer|FastJson|FastJSON|Sweet\.Jayson"],
        ["2_dotnet_Deserialization", "OnDeserializ|XmlSerializer|DataContractSerializer|FsPickler|JavaScriptSerializer|Json\.Net|SharpSerializerBinary|SharpSerializerXml|YamlDotNet|Xaml|TypeNameHandling|SimpleTypeResolver|JavaScriptTypeResolver|BinaryReader|BinaryWriter"],
        ["3_dotnet_viewState", "EnableViewState"],
        ["3_dotnet_console_WriteLine", "Console\.WriteLine"],
        ["3_dotnet_TripleDESCryptoServiceProvider", "TripleDESCryptoServiceProvider"],
        ["3_dotnet_unchecked", "unchecked"],
        ["3_dotnet_ReflectionPermission", "ReflectionPermission"],
        ["3_dotnet_htmlinputhidden", "htmlinputhidden"],
        ["3_dotnet_requestEncoding", "requestEncoding"],
        ["3_dotnet_CustomErrors", "CustomErrors"],
        ["3_dotnet_pipedinputstream", "pipedinputstream"],
        ["3_dotnet_objectstream", "objectstream"],
        ["3_dotnet_AuthenticateRequest", "AuthenticateRequest"],
        ["3_dotnet_AuthorizeRequest", "AuthorizeRequest"],
        ["3_dotnet_Session_OnStart", "Session_OnStart"],
        ["3_dotnet_SecurityCriticalAttribute", "SecurityCriticalAttribute"],
        ["3_dotnet_SecurityPermission", "SecurityPermission"],
        ["3_dotnet_SecurityAction", "SecurityAction"],
        ["3_dotnet_IntPtr", "IntPtr"],
        ["3_dotnet_SqlClient", "SqlClient"],
        ["3_dotnet_UnmanagedCode", "UnmanagedCode"],
        ["3_dotnet_Serializable", "Serializable"],
        ["3_dotnet_CharSet_Auto", "CharSet\.Auto"],
        ["3_dotnet_DllImport", "DllImport"],
        ["4_dotnet_ObjectInputStream", "ObjectInputStream"],
        ["4_dotnet_AllowInsecureDeserialization", "AllowInsecureDeserialization"],
        ["4_dotnet_System.Net.Cookie", "System\.Net\.Cookie"],
        ["4_dotnet_crypt", "RNGCryptoServiceProvider|System\.Security\.Cryptography|PBEParameterSpec|PasswordDeriveBytes"],
        ["4_dotnet_exec", "System\.Diagnostics\.Process|new Cli\s{1,$WILDCARD_SHORT}\(|Shell\s{1,$WILDCARD_SHORT}\(|Process\.Start"],
        ["4_dotnet_security_permission", "SecurityPermission|ReflectionPermission|CodeAccessPermission"],
        ["4_dotnet_database", "OdbcCommand|ExecuteNonQuery|ExecuteQuery"],

        ["1_general_uris_auth_info_narrow", "://[^ ]{1,$WILDCARD_SHORT}:[^ ]{1,$WILDCARD_SHORT}@"],
        ["1_general_con_str_sql_password", ";Password=", re.IGNORECASE],
        ["1_general_con_str_sql_pwd", ";Pwd=", re.IGNORECASE],
        ["1_general_aws_keys", "AWS_KEY|AWSKEY|AKIA", re.IGNORECASE],
        ["2_general_html_templating", "<%="],
        ["2_general_superuser", "super.?user", re.IGNORECASE],
        ["2_general_su-binary", "su.{0,3}binary", re.IGNORECASE],
        ["2_general_sudo", "sudo\s", re.IGNORECASE],
        ["2_general_uris_auth_info_wide", "[^ ]{1,$WILDCARD_SHORT}:[^ ]{1,$WILDCARD_SHORT}@"],
        ["2_general_jdbc_uri", "jdbc:", re.IGNORECASE],
        ["2_general_con_str_sqlserver", "Server=.{0,$WILDCARD_SHORT};Database=", re.IGNORECASE],
        ["2_general_con_str_localdb", ";Integrated.Security=", re.IGNORECASE],
        ["2_general_sql_injection", "sql.{0,$WILDCARD_SHORT}injection", re.IGNORECASE],
        ["2_general_xss_uppercase", "XSS", re.IGNORECASE],
        ["2_general_hacking_techniques_clickjacking", "click.{0,$WILDCARD_SHORT}jacking", re.IGNORECASE],
        ["2_general_hacking_techniques_xsrf", "xsrf", re.IGNORECASE],
        ["2_general_hacking_techniques_csrf", "csrf", re.IGNORECASE],
        ["2_general_hacking_techniques_buffer-overflow", "buffer.{0,$WILDCARD_SHORT}overflow", re.IGNORECASE],
        ["2_general_hacking_techniques_integer-overflow", "integer.{0,$WILDCARD_SHORT}overflow", re.IGNORECASE],
        ["2_general_obfuscation", "obfuscat", re.IGNORECASE],
        ["2_general_sql_create_login", "CREATE LOGIN", re.IGNORECASE],
        ["2_general_sql_pwdcompare", "PWDCOMPARE\(", re.IGNORECASE],
        ["2_general_sql_loginproperty", "LOGINPROPERTY\(", re.IGNORECASE],
        ["2_general_sql_sp_addlogin", "sp_addlogin", re.IGNORECASE],
        ["2_general_sql_with_password", "WITH PASSWORD =", re.IGNORECASE],
        ["2_general_sql_rmtpassword", "@rmtpassword", re.IGNORECASE],
        ["3_general_exec_narrow", "exec\s{0,$WILDCARD_SHORT}\(", re.IGNORECASE],
        ["3_general_eval_narrow", "eval\s{0,$WILDCARD_SHORT}\(", re.IGNORECASE],
        ["3_general_syscall_narrow", "sys.?call\s{0,$WILDCARD_SHORT}\(", re.IGNORECASE],
        ["3_general_system_narrow", "system\s{0,$WILDCARD_SHORT}\(", re.IGNORECASE],
        ["3_general_pipeline_narrow", "pipeline\s{0,$WILDCARD_SHORT}\("],
        ["3_general_popen_narrow", "popen\s{0,$WILDCARD_SHORT}\("],
        ["3_general_spawn_narrow", "spawn\s{0,$WILDCARD_SHORT}\("],
        ["3_general_session_timeout", "session-?\s?time-?\s?out", re.IGNORECASE],
        ["3_general_setcookie", "setcookie", re.IGNORECASE],
        ["3_general_serialise", "seriali[sz]e", re.IGNORECASE],
        ["3_general_creditcard", "credit.?card", re.IGNORECASE],
        ["3_general_non_ssl_uris_ftp", "ftp://", re.IGNORECASE],
        ["3_general_non_ssl_uris_socket", "socket://", re.IGNORECASE],
        ["3_general_non_ssl_uris_imap", "imap://", re.IGNORECASE],
        ["3_general_non_ssl_uris_file", "file://", re.IGNORECASE],
        ["3_general_con_str_trusted_sqlserver", ";Trusted_Connection="],
        ["3_general_scheme", "scheme", re.IGNORECASE],
        ["3_general_schema", "schema", re.IGNORECASE],
        ["3_general_wsdl", "wsdl", re.IGNORECASE],
        ["3_general_webview", "webview", re.IGNORECASE],
        ["3_general_directory_listing", "directory.{0,$WILDCARD_SHORT}listing"],
        ["3_general_backticks", "\`.{2,$WILDCARD_LONG}\`"],
        ["3_general_sql_select", "SELECT.{0,$WILDCARD_LONG}FROM", re.IGNORECASE],
        ["3_general_sql_insert", "INSERT.{0,$WILDCARD_SHORT}INTO", re.IGNORECASE],
        ["3_general_sql_delete", "DELETE.{0,$WILDCARD_LONG}WHERE", re.IGNORECASE],
        ["3_general_sql_sqlcipher", "sqlcipher", re.IGNORECASE],
        ["3_general_sql_query", "sql_query", re.IGNORECASE],
        ["3_general_query", "query\s{0,$WILDCARD_SHORT}\(", re.IGNORECASE],
        ["3_general_dollar_sql", "\$sql", re.IGNORECASE],
        ["3_general_base64_word", "base64", re.IGNORECASE],
        ["3_general_swear_stupid", "stupid", re.IGNORECASE],
        ["3_general_swear_fuck", "fuck", re.IGNORECASE],
        ["3_general_swear_shit", "shit", re.IGNORECASE],
        ["3_general_swear_crap", "crap", re.IGNORECASE],
        ["3_general_ip-addresses", "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"],
        ["3_general_referer", "referer", re.IGNORECASE],
        ["3_general_sqli_generic", "from\s.{0,$WILDCARD_LONG}\swhere\s.{0,$WILDCARD_LONG}", re.IGNORECASE],
        ["3_general_ldap_generic", "\(&\(.{0,$WILDCARD_SHORT}="],
        ["3_general_sleep_generic", "sleep", re.IGNORECASE],
        ["4_general_deny", "[Dd]eny"],
        ["4_general_exec_wide", "exec", re.IGNORECASE],
        ["4_general_eval_wide", "eval", re.IGNORECASE],
        ["4_general_syscall_wide", "sys.?call", re.IGNORECASE],
        ["4_general_system_wide", "system", re.IGNORECASE],
        ["4_general_pipeline_wide", "pipeline", re.IGNORECASE],
        ["4_general_popen_wide", "popen", re.IGNORECASE],
        ["4_general_spawn_wide", "spawn", re.IGNORECASE],
        ["4_general_chgrp", "chgrp", re.IGNORECASE],
        ["4_general_chown", "chown", re.IGNORECASE],
        ["4_general_chmod", "chmod", re.IGNORECASE],
        ["4_general_session_timeout", "time-?\s?out", re.IGNORECASE],
        ["4_general_relative_paths", "\./"],
        ["4_general_debugger", "debugger", re.IGNORECASE],
        ["4_general_kernel", "Kernel", re.IGNORECASE],
        ["4_general_hack", "hack", re.IGNORECASE],
        ["4_general_crack", "crack", re.IGNORECASE],
        ["4_general_trick", "trick", re.IGNORECASE],
        ["4_general_exploit", "xploit", re.IGNORECASE],
        ["4_general_bypass", "bypass", re.IGNORECASE],
        ["4_general_backdoor", "back.{0,$WILDCARD_SHORT}door", re.IGNORECASE],
        ["4_general_backd00r", "back.{0,$WILDCARD_SHORT}d00r", re.IGNORECASE],
        ["4_general_fake", "fake", re.IGNORECASE],
        ["4_general_https_urls", "https://", re.IGNORECASE],
        ["4_general_http_urls", "http://", re.IGNORECASE],
        ["4_general_hidden", "hidden", re.IGNORECASE],
        ["4_general_sql_sqlite", "sqlite", re.IGNORECASE],
        ["4_general_sql_cursor", "cursor", re.IGNORECASE],
        ["4_general_base64_content", "(?:[A-Za-z0-9+/]{4}){2,}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)"],
        ["4_general_base64_urlsafe", "(?:[A-Za-z0-9_-]{4}){2,}(?:[A-Za-z0-9_-]{2}==|[A-Za-z0-9_-]{3}=)"],
        ["5_general_update", "update", re.IGNORECASE],
        ["5_general_backup", "backup", re.IGNORECASE],
        ["5_general_email", "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\b"],
        ["5_general_todo", "TODO", re.IGNORECASE],
        ["5_general_workaround", "workaround", re.IGNORECASE],
        ["5_general_gpl1", "GNU\sGPL", re.IGNORECASE],
        ["5_general_gpl2", "GPLv2", re.IGNORECASE],
        ["5_general_gpl3", "GPLv3", re.IGNORECASE],
        ["5_general_gpl4", "GPL\sVersion", re.IGNORECASE],
        ["5_general_gpl5", "General\sPublic\sLicense", re.IGNORECASE],
        ["5_general_debug", "debug", re.IGNORECASE],
        ["5_general_http_vars", "HTTP_.{0,$WILDCARD_SHORT}_VARS", re.IGNORECASE],
        ["5_general_http_files", "HTTP_.{0,$WILDCARD_SHORT}_FILES", re.IGNORECASE],
        ["5_general_HTTP_X_FORWARDED_FOR", "HTTP_X_FORWARDED_FOR", re.IGNORECASE],
        ["5_general_REMOTE_ADDR", "REMOTE_ADDR", re.IGNORECASE],
        ["5_general_user_agent", "USER_AGENT", re.IGNORECASE],
        ["5_general_user-agent", "User-Agent", re.IGNORECASE],
        ["5_general_websocket", "ws:|wss:|WebSocket", re.IGNORECASE],
        ["9_general_serialization", "Serialization|SerializationFormatter|Serializable|SerializeObject|SerializationBinder|JsonSerializer|JsonSerializerSettings|DleserializeObject|ISerializable"],
        ["9_general_database", "xp_cmdshell", re.IGNORECASE],

        ["2_hmac_with_user_input", "hash_hmac\s{0,$WILDCARD_SHORT}\(.{0,$WILDCARD_LONG}\\\$_", re.IGNORECASE],

        ["4_html_upload_form_tag", "multipart/form-data", re.IGNORECASE],
        ["4_html_upload_input_tag", "type=.?file", re.IGNORECASE],
        ["6_html_autocomplete", "autocomplete", re.IGNORECASE],

        ["2_ios_kCFStreamSSLAllowsExpiredCertificates", "kCFStreamSSLAllowsExpiredCertificates"],
        ["2_ios_kCFStreamSSLAllowsExpiredRoots", "kCFStreamSSLAllowsExpiredRoots"],
        ["2_ios_kCFStreamSSLAllowsAnyRoot", "kCFStreamSSLAllowsAnyRoot"],
        ["2_ios_kCFStreamSSLValidatesCertificateChain", "kCFStreamSSLValidatesCertificateChain"],
        ["2_ios_kSecTrustOptionAllowExpired", "kSecTrustOptionAllowExpired"],
        ["2_ios_kSecTrustOptionAllowExpiredRoot", "kSecTrustOptionAllowExpiredRoot"],
        ["2_ios_NSAllowsArbitraryLoads", "NSAllowsArbitraryLoads"],
        ["2_ios_sqlite3_exec", "sqlite3_exec\("],
        ["2_ios_fts3_tokenizer", "fts3_tokenizer"],
        ["2_ios_allowLocalhostRequest", "allowLocalhostRequest"],
        ["2_ios_GTM_ALLOW_INSECURE_REQUESTS", "GTM_ALLOW_INSECURE_REQUESTS"],
        ["2_ios_registerForRemoteNotificationTypes", "registerForRemoteNotificationTypes"],
        ["2_ios_CFStringCreateWithFormat", "CFStringCreateWithFormat"],
        ["3_ios_loadHTMLString", "loadHTMLString"],
        ["3_ios_stringByEvaluatingJavaScriptFromString", "stringByEvaluatingJavaScriptFromString"],
        ["3_ios_canAuthenticateAgainstProtectionSpace", "canAuthenticateAgainstProtectionSpace"],
        ["3_ios_didReceiveAuthenticationChallenge", "didReceiveAuthenticationChallenge"],
        ["3_ios_willSendRequestForAuthenticationChallenge", "willSendRequestForAuthenticationChallenge"],
        ["3_ios_continueWithoutCredentialForAuthenticationChallenge", "continueWithoutCredentialForAuthenticationChallenge"],
        ["3_ios_ValidatesSecureCertificate", "ValidatesSecureCertificate"],
        ["3_ios_setValidatesSecureCertificate", "setValidatesSecureCertificate"],
        ["3_ios_setAllowsAnyHTTPSCertificate", "setAllowsAnyHTTPSCertificate"],
        ["3_ios_NSHTTPCookieAcceptPolicy", "NSHTTPCookieAcceptPolicy"],
        ["3_ios_file_access_nsfileprotection", "NSFileProtection"],
        ["3_ios_keychain_kSecAttrAccessibleWhenUnlocked", "kSecAttrAccessibleWhenUnlocked[^T]"],
        ["3_ios_keychain_kSecAttrAccessibleAfterFirstUnlock", "kSecAttrAccessibleAfterFirstUnlock[^T]"],
        ["3_ios_keychain_kSecAttrAccessibleWhenPasscodeSet", "kSecAttrAccessibleWhenPasscodeSet[^T]"],
        ["3_ios_keychain_kSecAttrAccessibleAlways", "kSecAttrAccessibleAlways[^T]"],
        ["3_ios_keychain_kSecAttrSynchronizable", "kSecAttrSynchronizable"],
        ["3_ios_kCFStreamPropertySSLSettings", "kCFStreamPropertySSLSettings"],
        ["3_ios_kCFStreamSSLPeerName", "kCFStreamSSLPeerName"],
        ["3_ios_kSecTrustOptionImplicitAnchors", "kSecTrustOptionImplicitAnchors"],
        ["3_ios_NSStreamSocketSecurityLevel", "NSStreamSocketSecurityLevel"],
        ["3_ios_sourceApplication", "sourceApplication:"],
        ["3_ios_SecRandomCopyBytes", "SecRandomCopyBytes"],
        ["3_ios_allowScreenShot", "allowScreenShot"],
        ["3_ios_UIPasteboardNameGeneral", "UIPasteboardNameGeneral"],
        ["3_ios_secureTextEntry", "secureTextEntry"],
        ["3_ios_allowedInsecureSchemes", "allowedInsecureSchemes"],
        ["3_ios_syslog", "syslog\("],
        ["3_ios_UnsafePointer", "UnsafePointer"],
        ["3_ios_UnsafeMutablePointer", "UnsafeMutablePointer"],
        ["3_ios_UnsafeCollection", "UnsafeCollection"],
        ["4_ios_file_access_fileURLWithPath", "fileURLWithPath"],
        ["4_ios_file_access_NSURL", "NSURL"],
        ["4_ios_file_access_NSURLConnection", "NSURLConnection"],
        ["4_ios_file_access_writeToFile", "writeToFile"],
        ["4_ios_loadRequest", "loadRequest"],
        ["4_ios_file_access_nsfilemanager", "NSFileManager"],
        ["4_ios_file_access_nspersistantstorecoordinator", "NSPersistantStoreCoordinator"],
        ["4_ios_keychain_ksecattraccessible", "kSecAttrAccessible"],
        ["4_ios_keychain_secitemadd", "SecItemAdd"],
        ["4_ios_keychain_SecItemUpdate", "SecItemUpdate"],
        ["4_ios_keychain_SecItemCopyMatching", "SecItemCopyMatching"],
        ["4_ios_keychain_KeychainItemWrapper", "KeychainItemWrapper"],
        ["4_ios_willCacheResponse", "willCacheResponse"],
        ["4_ios_CFFTPStream", "CFFTPStream"],
        ["4_ios_NSStreamin", "NSStreamin"],
        ["4_ios_NSXMLParser", "NSXMLParser"],
        ["4_ios_UIPasteboardName", "UIPasteboardName"],
        ["4_ios_FTPURL", "FTPURL"],
        ["4_ios_IOBluetooth", "IOBluetooth"],
        ["4_ios_string_format_initWithFormat_narrow", "initWithFormat:[^@]"],
        ["4_ios_string_format_informativeTextWithFormat_narrow", "informativeTextWithFormat:[^@]"],
        ["4_ios_string_format_format_narrow", "format:[^@]"],
        ["4_ios_string_format_stringWithFormat_narrow", "stringWithFormat:[^@]"],
        ["4_ios_string_format_stringByAppendingFormat_narrow", "stringByAppendingFormat:[^@]"],
        ["4_ios_string_format_appendFormat_narrow", "appendFormat:[^@]"],
        ["4_ios_string_format_alertWithMessageText_narrow", "alertWithMessageText:[^@]"],
        ["4_ios_string_format_predicateWithFormat_narrow", "predicateWithFormat:[^@]"],
        ["4_ios_string_format_NSRunAlertPanel_narrow", "NSRunAlertPanel:[^@]"],
        ["4_ios_CFBundleDocumentTypes", "CFBundleDocumentTypes"],
        ["4_ios_CFBundleURLTypes", "CFBundleURLTypes"],
        ["4_ios_sqlite3_prepare", "sqlite3_prepare"],
        ["4_ios_CFDataRef", "CFDataRef"],
        ["4_ios_CFStringRef", "CFStringRef"],
        ["4_ios_NSString", "NSString"],
        ["4_ios_CFStringAppendFormat", "CFStringAppendFormat"],
        ["5_ios_file_access_nsfile", "NSFile"],
        ["5_ios_writeToUrl", "writeToUrl"],
        ["5_ios_UIWebView", "UIWebView"],
        ["5_ios_shouldStartLoadWithRequest", "shouldStartLoadWithRequest"],
        ["5_ios_file_access_nsdata", "NSData"],
        ["5_ios_keychain_security_h", "Security\.h"],
        ["5_ios_CFStream", "CFStream"],
        ["5_ios_CFHTTP", "CFHTTP"],
        ["5_ios_CFNetServices", "CFNetServices"],
        ["5_ios_string_format_initWithFormat_wide", "initWithFormat:"],
        ["5_ios_string_format_informativeTextWithFormat_wide", "informativeTextWithFormat:"],
        ["5_ios_string_format_format_wide", "format:"],
        ["5_ios_string_format_stringWithFormat_wide", "stringWithFormat:"],
        ["5_ios_string_format_stringByAppendingFormat_wide", "stringByAppendingFormat:"],
        ["5_ios_string_format_appendFormat_wide", "appendFormat:"],
        ["5_ios_string_format_alertWithMessageText_wide", "alertWithMessageText:"],
        ["5_ios_string_format_predicateWithFormat_wide", "predicateWithFormat:"],
        ["5_ios_string_format", ":format"],
        ["5_ios_string_format_NSRunAlertPanel_wide", "NSRunAlertPanel:"],
        ["5_ios_string_format_url_handler_handleOpenURL", "handleOpenURL"],
        ["5_ios_string_format_url_handler_openURL", "openURL"],
        ["5_ios_NSCoding", "NSCoding"],
        ["5_ios_CFBundle", "CFBundle"],
        ["5_ios_NSBundle", "NSBundle"],
        ["5_ios_NSKeyedUnarchiverDelegate", "NSKeyedUnarchiverDelegate"],
        ["5_ios_didDecodeObject", "didDecodeObject"],
        ["5_ios_awakeAfterUsingCoder", "awakeAfterUsingCoder"],
        ["6_ios_NSLog", "NSLog\("],

        ["1_java_jsp_property_to_html_xss", "<%=\s{0,$WILDCARD_SHORT}[A-Za-z0-9_]{1,$WILDCARD_LONG}.get[A-Za-z0-9_]{1,$WILDCARD_LONG}\("],
        ["1_java_jsp_out_print_to_html_xss2", "out.printl?n?\(\"<.{1,$WILDCARD_LONG}\+.{1,$WILDCARD_LONG}\);"],
        ["2_java_crypto_new-SecretKeySpec", "new\sSecretKeySpec\("],
        ["2_java_crypto_new-PBEKeySpec_str", "new\sPBEKeySpec\(\""],
        ["2_java_string_comparison_equals_hash", "equals\(.{0,$WILDCARD_SHORT}[Hh][Aa][Ss][Hh]"],
        ["2_java_string_comparison_equalsIgnoreCase_hash", "equalsIgnoreCase\(.{0,$WILDCARD_SHORT}[Hh][Aa][Ss][Hh]"],
        ["2_java_jsp_xss_escape", "escape\s{0,$WILDCARD_SHORT}=\s{0,$WILDCARD_SHORT}'?\"?\s{0,$WILDCARD_SHORT}false"],
        ["2_java_jsp_xss_escapexml", "escapeXml\s{0,$WILDCARD_SHORT}=\s{0,$WILDCARD_SHORT}'?\"?\s{0,$WILDCARD_SHORT}false"],
        ["2_java_spring_stripUnsafeHTML", "stripUnsafeHTML"],
        ["2_java_spring_stripEncodeUnsafeHTML", "stripEncodeUnsafeHTML"],
        ["2_java_struts_deactivated_validation", "validate\s{0,$WILDCARD_SHORT}=\s{0,$WILDCARD_SHORT}'?\"?false"],
        ["2_java_struts_devMode", "struts\.devMode"],
        ["3_java_writeObject", "writeObject"],
        ["3_java_readObject", "readObject"],
        ["3_java_readObjectNodData", "readObjectNodData"],
        ["3_java_readResolve", "readResolve"],
        ["3_java_readExternal", "readExternal"],
        ["3_java_readUnshared", "readUnshared"],
        ["3_java_fromXML", "fromXML"],
        ["3_java_readValue", "readValue"],
        ["3_java_XMLdecoder", "XMLdecoder"],
        ["3_java_serialization_genetic", "readClassAndObject|readObjectOrNull|BurlapInput|BurlapOutput|org\.codehaus\.castor|jsonToJava|JsonObjectsToJava|JsonReader|ObjectMapper|enableDefaultTyping|JsonTypeInfo|parseObject|useRuntimeType|genson\.deserialize|org\.red5\.io|loadType|YamlReader|yamlbeans|com\.owlike\.genson\.Genson|com\.alibaba\.fastjson\.JSON"],
        ["3_java_x-java-serialized-object", "application/x-java-serialized-object"],
        ["3_java_serialFilter", "serialFilter"], # https://youtu.be/Lv9BC_bYaI8
        ["3_java_autoDeserialize", "autoDeserialize"], # https://youtu.be/Lv9BC_bYaI8?t=1701
        ["3_java_queryInterceptors", "queryInterceptors"], # https://youtu.be/Lv9BC_bYaI8?t=1750
        ["3_java_crypto_new-PBEKeySpec", "new\sPBEKeySpec\("],
        ["3_java_crypto_generateKey", "\.generateKey\("],
        ["3_java_format_string1", "String\.format\(\s{0,$WILDCARD_SHORT}\"[^\"]{1,$WILDCARD_LONG}\"\s{0,$WILDCARD_SHORT}\+"],
        ["3_java_servlet_setMaxInactiveInterval", "setMaxInactiveInterval\("],
        ["3_java_ssl_checkValidity", "\.checkValidity\("],
        ["3_java_checkServerTrusted", "checkServerTrusted\("],
        ["3_java_getPeerCertificates", "getPeerCertificates\("],
        ["3_java_getPeerCertificateChain", "getPeerCertificateChain\("],
        ["3_java_jsp_file_upload", "<s:file\s"],
        ["3_java_spring_mass_assignment", "DataBinder\.setAllowedFields"],
        ["3_java_xxe_candidates", "SAXParserFactory|DOM4J|XMLInputFactory|TransformerFactory|javax\.xml\.validation\.Validator|SchemaFactory|SAXTransformerFactory|XMLReader|SAXBuilder|SAXReader|Unmarshaller|XPathExpression|DOMSource|StAXSource|DocumentBuilderFactory|XMLInputFactory"],
        ["4_java_crypto_keygenerator-getinstance", "KeyGenerator\.getInstance\("],
        ["4_java_crypto_cipher_getInstance", "Cipher\.getInstance\("],
        ["4_java_crypto_messagedigest", "messagedigest"],
        ["4_java_crypto_keypairgenerator", "KeyPairGenerator\("],
        ["4_java_http_setHeader", "\.setHeader\("],
        ["4_java_http_sendRedirect", "\.sendRedirect\("],
        ["4_java_http_addHeader", "\.addHeader\("],
        ["4_java_http_getHeaders", "\.getHeaders\("],
        ["4_java_http_getCookies", "\.getCookies\("],
        ["4_java_http_getRemoteHost", "\.getRemoteHost\("],
        ["4_java_http_getRemoteUser", "\.getRemoteUser\("],
        ["4_java_http_isSecure", "\.isSecure\("],
        ["4_java_http_getRequestedSessionId", "\.getRequestedSessionId\("],
        ["4_java_format_string2", "String\.format\(\s{0,$WILDCARD_SHORT}[^\"]"],
        ["4_java_javax-validation", "javax.validation"],
        ["4_java_jsp_redirect", "\.sendRedirect\("],
        ["4_java_jsp_forward_1", "\.forward\("],
        ["4_java_jsp_forward_2", ":forward"],
        ["4_java_jsp_property_to_html_xss", "\.getParameter\("],
        ["4_java_spring_requestMapping", "@RequestMapping\("],
        ["4_java_spring_servletMapping", "<servlet-mapping>"],
        ["5_java_crypto_random", "new Random\("],
        ["5_java_math_random", "Math.random\("],
        ["5_java_sql_execute", "execute.{0,$WILDCARD_SHORT}\("],
        ["5_java_sql_addBatch", "addBatch\("],
        ["5_java_sql_prepareStatement", "prepareStatement\("],
        ["5_java_http_addCookie", "\.addCookie\("],
        ["5_java_http_getContentType", "\.getContentType\("],
        ["5_java_http_getLocalName", "\.getLocalName\("],
        ["5_java_ProcessBuilder", "ProcessBuilder"],
        ["5_java_persistent_columns_in_database", "@Column\("],
        ["5_java_persistent_tables_in_database", "@Table\("],
        ["5_java_SSLSocketFactory", "SSLSocketFactory"],
        ["5_java_runtime_exec_1", "getRuntime\(\)\.exec\("],
        ["5_java_runtime_exec_2", "Process.{0,$WILDCARD_SHORT}\.exec\("],
        ["5_java_setAttribute", "\.setAttribute\("],
        ["5_java_StreamTokenizer", "StreamTokenizer"],
        ["5_java_getResourceAsStream", "getResourceAsStream"],
        ["5_java_isTrusted", "isTrusted"],
        ["6_java_string_comparison_equals", "equals\("],
        ["6_java_string_comparison_equalsIgnoreCase", "equalsIgnoreCase\("],
        ["6_java_http_getParameter", "\.getParameter.{0,$WILDCARD_SHORT}\("],
        ["6_java_persistent_beans", "@Entity|@ManyToOne|@OneToMany|@OneToOne|@Table|@Column"],
        ["6_java_confidential_data_in_strings_password", "string .{0,$WILDCARD_SHORT}password"],
        ["6_java_confidential_data_in_strings_secret", "string .{0,$WILDCARD_SHORT}secret"],
        ["6_java_confidential_data_in_strings_key", "string .{0,$WILDCARD_SHORT}key"],
        ["6_java_confidential_data_in_strings_cvv", "string .{0,$WILDCARD_SHORT}cvv"],
        ["6_java_confidential_data_in_strings_user", "string .{0,$WILDCARD_SHORT}user"],
        ["6_java_confidential_data_in_strings_passcode", "string .{0,$WILDCARD_SHORT}passcode"],
        ["6_java_confidential_data_in_strings_passphrase", "string .{0,$WILDCARD_SHORT}passphrase"],
        ["6_java_confidential_data_in_strings_pin", "string .{0,$WILDCARD_SHORT}pin"],
        ["6_java_confidential_data_in_strings_credit", "string .{0,$WILDCARD_SHORT}credit"],
        ["6_java_getruntime", "getRuntime\("],
        ["6_java_apache_common_openProcess", "openProcess\("],
        ["6_java_printStackTrace", "\.printStackTrace\("],
        ["7_java_crypto_javax-crypto", "javax.crypto"],
        ["7_java_crypto_bouncycastle", "bouncy.{0,$WILDCARD_SHORT}castle"],
        ["7_java_io_java_net", "java\.net\."],
        ["7_java_io_java_io", "java\.io\."],
        ["7_java_io_javax_servlet", "javax\.servlet"],
        ["7_java_io_apache_http", "org\.apache\.http"],
        ["8_java_string_comparison1", "toString\(\s{0,$WILDCARD_SHORT}\)\s{0,$WILDCARD_SHORT}=="],
        ["8_java_string_comparison2", "==\s{0,$WILDCARD_SHORT}toString\(\s{0,$WILDCARD_SHORT}\)"],
        ["8_java_string_comparison3", "==\s{0,$WILDCARD_SHORT}\""],
        ["8_java_backdoor_as_unicode", "\\\\u00..\\\\u00.."],
        ["9_java_strings", "\"[^\"]{4,500}\""],
        
        ["2_js_insecure_JSON_parser", "Eaeflnr-u"],
        ["3_js_new_function_eval", "new\sFunction.{0,$WILDCARD_SHORT}"],
        ["3_js_localStorage", "localStorage"],
        ["3_js_sessionStorage", "sessionStorage"],
        ["3_js_createElement_script", "createElement.{0,$WILDCARD_SHORT}script"],
        ["3_js_document_domain", "document\.domain"],
        ["3_js_document_cookie", "document\.cookie"],
        ["3_js_postMessage", "postMessage\("],
        ["3_js_addEventListener_message", "addEventListener.{0,$WILDCARD_SHORT}message"],
        ["3_js_AllowScriptAccess", "AllowScriptAccess"],
        ["3_js_mayscript", "mayscript"],
        ["4_js_dom_xss_location-hash", "location\.hash"],
        ["4_js_dom_xss_location-href", "location\.href"],
        ["4_js_dom_xss_location-pathname", "location\.pathname"],
        ["4_js_dom_xss_location-search", "location\.search"],
        ["4_js_dom_xss_appendChild", "\.appendChild\("],
        ["4_js_dom_xss_document_location", "document\.location"],
        ["4_js_dom_xss_window-location", "window\.location"],
        ["4_js_dom_xss_document-referrer", "document\.referrer"],
        ["4_js_dom_xss_document-URL", "document\.URL"],
        ["4_js_dom_xss_document-write", "document\.writel?n?\(", re.IGNORECASE],
        ["4_js_dom_xss_innerHTML", "\.innerHTML\s{0,$WILDCARD_SHORT}="],
        ["4_js_react_dom_xss_dangerouslySetInnerHTML", "DangerouslySetInnerHTML\s{0,$WILDCARD_SHORT}"],
        ["4_js_react_dom_xss_trustAsHtml", "trustAsHtml\s{0,$WILDCARD_SHORT}"],
        ["4_js_dom_xss_outerHTML", "\.outerHTML\s{0,$WILDCARD_SHORT}="],
        ["4_js_console", "console\."],
        ["4_js_postMessage", "\.postMessage\s{0,$WILDCARD_SHORT}\("],
        ["4_js_execScript", "\.execScript\s{0,$WILDCARD_SHORT}\("],
        ["4_js_setInterval", "\.setInterval\s{0,$WILDCARD_SHORT}\("],
        ["4_js_setTimeout", "\.setTimeout\s{0,$WILDCARD_SHORT}\("],
        
        ["4_malware_viagra", "viagra"],
        ["4_malware_potenzmittel", "potenzmittel"],
        ["4_malware_pharmacy", "pharmacy"],
        ["4_malware_drug", "drug"],
        
        ["2_mobile_root_detection_root-detection", "root.{0,$WILDCARD_SHORT}detection"],
        ["2_mobile_root_detection_root-device", "root.{0,$WILDCARD_SHORT}Device"],
        ["2_mobile_root_detection_isRooted", "is.{0,$WILDCARD_SHORT}rooted"],
        ["2_mobile_root_detection_detectRoot", "detect.{0,$WILDCARD_SHORT}root"],
        ["2_mobile_jailbreak", "jail.{0,$WILDCARD_SHORT}break"],
        
        ["3_modsecurity_ctl_auditEngine", "ctl:auditEngine"],
        ["3_modsecurity_ctl_ruleEngine", "ctl:ruleEngine"],
        ["3_modsecurity_ctl_ruleRemoveById", "ctl:ruleRemoveById"],
        ["4_modsecurity_exec", "exec:"],
        ["4_modsecurity_append", "append:"],
        ["4_modsecurity_SecContentInjection", "SecContentInjection"],
        ["4_modsecurity_inspectFile", "@inspectFile"],
        ["4_modsecurity_SecAuditEngine", "SecAuditEngine"],
        ["4_modsecurity_SecAuditLogParts", "SecAuditLogParts"],
        ["5_modsecurity_block", "block"],
        
        ["1_php_verifypeer-verifypeer", "CURLOPT_SSL_VERIFYPEER"],
        ["1_php_verifypeer-verifyhost", "CURLOPT_SSL_VERIFYHOST"],
        ["1_php_gnutls-certificate-verify-peers", "gnutls_certificate_verify_peers"],
        ["1_php_fsockopen", "fsockopen\s{0,$WILDCARD_SHORT}\("],
        ["1_php_echo_low_volume_POST", "echo.{0,$WILDCARD_LONG}\\\$_POST"],
        ["1_php_echo_low_volume_GET", "echo.{0,$WILDCARD_LONG}\\\$_GET"],
        ["1_php_echo_low_volume_COOKIE", "echo.{0,$WILDCARD_LONG}\\\$_COOKIE"],
        ["1_php_echo_low_volume_REQUEST", "echo.{0,$WILDCARD_LONG}\\\$_REQUEST"],
        ["1_php_echo_low_volume_SERVER", "echo.{0,$WILDCARD_LONG}\\\$_SERVER"],
        ["1_php_echo_low_volume_FILES", "echo.{0,$WILDCARD_LONG}\\\$_FILES"],
        ["1_php_echo_low_volume_ENV", "echo.{0,$WILDCARD_LONG}\\\$_ENV"],
        ["1_php_echo_low_volume_SESSION", "echo.{0,$WILDCARD_LONG}\\\$_SESSION"],
        ["1_php_print_low_volume_POST", "print.{0,$WILDCARD_LONG}\\\$_POST"],
        ["1_php_print_low_volume_GET", "print.{0,$WILDCARD_LONG}\\\$_GET"],
        ["1_php_print_low_volume_COOKIE", "print.{0,$WILDCARD_LONG}\\\$_COOKIE"],
        ["1_php_print_low_volume_REQUEST", "print.{0,$WILDCARD_LONG}\\\$_REQUEST"],
        ["1_php_print_low_volume_SERVER", "print.{0,$WILDCARD_LONG}\\\$_SERVER"],
        ["1_php_print_low_volume_FILES", "print.{0,$WILDCARD_LONG}\\\$_FILES"],
        ["1_php_print_low_volume_ENV", "print.{0,$WILDCARD_LONG}\\\$_ENV"],
        ["1_php_print_low_volume_SESSION", "print.{0,$WILDCARD_LONG}\\\$_SESSION"],
        ["2_php_passthru", "passthru\s{0,$WILDCARD_SHORT}\("],
        ["2_php_shell_exec", "shell_exec\s{0,$WILDCARD_SHORT}\("],
        ["2_php_proc_open", "proc_open\s{0,$WILDCARD_SHORT}\("],
        ["2_php_proc_close", "proc_close\s{0,$WILDCARD_SHORT}\("],
        ["2_php_proc_get_status", "proc_get_status\s{0,$WILDCARD_SHORT}\("],
        ["2_php_proc_nice", "proc_nice\s{0,$WILDCARD_SHORT}\("],
        ["2_php_proc_terminate", "proc_terminate\s{0,$WILDCARD_SHORT}\("],
        ["2_php_pcntl_exec", "pcntl_exec\s{0,$WILDCARD_SHORT}\("],
        ["2_php_escapeshell", "escapeshell"],
        ["2_php_fopen", "fopen\s{0,$WILDCARD_SHORT}\("],
        ["2_php_readfile", "readfile\s{0,$WILDCARD_SHORT}\("],
        ["3_php_unserialize", "unserialize\s{0,$WILDCARD_SHORT}\("],
        ["3_php_serialize", "serialize\s{0,$WILDCARD_SHORT}\("],
        ["3_php_phpinfo", "phpinfo"],
        ["3_php_proc", "proc_"],
        ["3_php_file_get_contents", "file_get_contents\s{0,$WILDCARD_SHORT}\("],
        ["3_php_sql_pg_query", "pg_query\s{0,$WILDCARD_SHORT}\("],
        ["3_php_sql_mysqli", "mysqli_.{1,$WILDCARD_SHORT}\("],
        ["3_php_sql_mysql", "mysql_.{1,$WILDCARD_SHORT}\("],
        ["3_php_sql_mssql", "mssql_.{1,$WILDCARD_SHORT}\("],
        ["3_php_sql_odbc_exec", "odbc_exec\s{0,$WILDCARD_SHORT}\("],
        ["4_php_get", "\$_GET"],
        ["4_php_post", "\$_POST"],
        ["4_php_cookie", "\$_COOKIE"],
        ["4_php_request", "\$_REQUEST"],
        ["4_php_session", "\$_SESSION"],
        ["4_php_imagecreatefrom", "imagecreatefrom"],
        ["4_php_link", "link\s{0,$WILDCARD_SHORT}\("],
        ["4_php_file_include", "file_include\s{0,$WILDCARD_SHORT}\("],
        ["4_php_include", "include\s{0,$WILDCARD_SHORT}\("],
        ["4_php_include_once", "include_once\s{0,$WILDCARD_SHORT}\("],
        ["4_php_require", "require\s{0,$WILDCARD_SHORT}\("],
        ["4_php_require_once", "require_once\s{0,$WILDCARD_SHORT}\("],
        ["4_php_extract", "extract\s{0,$WILDCARD_SHORT}\("],
        ["5_php_mkdir", "mkdir\s{0,$WILDCARD_SHORT}\("],
        ["5_php_chmod", "chmod\s{0,$WILDCARD_SHORT}\("],
        ["5_php_chown", "chown\s{0,$WILDCARD_SHORT}\("],
        ["5_php_rmdir", "rmdir\s{0,$WILDCARD_SHORT}\("],
        ["5_php_echo_high_volume", "echo"],
        ["5_php_print_high_volume", "print"],
        ["5_php_rand", "rand\s{0,$WILDCARD_SHORT}\("],
        ["5_php_assert", "assert\s{0,$WILDCARD_SHORT}\("],
        ["5_php_preg_replace", "preg_replace\s{0,$WILDCARD_SHORT}\("],
        ["5_php_create_function", "create_function"],
        ["5_php_is_dir", "is_dir"],
        ["5_php_file_exists", "file_exists"],
        ["5_php_unlink", "unlink"],
        ["5_php_show_source", "show_source"],
        ["6_php_type_unsafe_comparison", "[^=]==[^=]"],
        ["7_php_file", "file\s{0,$WILDCARD_SHORT}\("],
        ["7_php_ffi", "FFI::"],
        ["7_php_oci_parse", "oci_parse"],
        ["5_php_getenv", "getenv\s{0,$WILDCARD_SHORT}\("],
        ["5_php_putenv", "putenv\s{0,$WILDCARD_SHORT}\("],
        ["9_php_construct", "__construct"],
        ["9_php_destruct", "__destruct"],
        ["9_php_wakeup", "__wakeup"],
        ["9_php_to_string", "__toString"],
        ["9_php_database", "mysql_query|mssql_query|pg_query|bind_param"],
        
        ["2_python_subprocess_shell_true", "shell=True"],
        ["2_python_shutil_copyfile", "copyfile\s{0,$WILDCARD_SHORT}\("],
        ["3_python_input_function", "input\s{0,$WILDCARD_SHORT}\("],
        ["3_python_assert_statement", "assert\s{1,$WILDCARD_SHORT}"],
        ["3_python_float_equality_left", "\d\.\d{1,$WILDCARD_SHORT}\s{1,$WILDCARD_SHORT}==\s{1,$WILDCARD_SHORT}"],
        ["3_python_float_equality_right", "\s{1,$WILDCARD_SHORT}==\s{1,$WILDCARD_SHORT}\d\.\d{1,$WILDCARD_SHORT}"],
        ["3_python_float_equality_general", "\s{1,$WILDCARD_SHORT}==\s{1,$WILDCARD_SHORT}"],
        ["3_python_double_underscore_general", "self\.__"],
        ["3_python_double_underscore_code", "__code__"],
        ["3_python_tempfile_mktemp", "mktemp\s{0,$WILDCARD_SHORT}\("],
        ["3_python_shutil_move", "move\s{0,$WILDCARD_SHORT}\("],
        ["3_python_yaml_import", "import\s{0,$WILDCARD_SHORT}yaml"],
        ["3_python_pickle_import", "import\s{0,$WILDCARD_SHORT}pickle"],
        ["3_python_pickle_from", "from\s{0,$WILDCARD_SHORT}pickle"],
        ["3_python_shelve_import", "import\s{0,$WILDCARD_SHORT}shelve"],
        ["3_python_shelve_from", "from\s{0,$WILDCARD_SHORT}shelve"],
        ["3_python_jinja2_import", "import\s{0,$WILDCARD_SHORT}jinja2"],
        ["3_python_jinja2_from", "from\s{0,$WILDCARD_SHORT}jinja2"],
        ["3_python_yaml_load", "yaml\.load"],
        ["3_python_yaml_dump", "yaml\.dump"],
        ["3_python_pickle_loads", "pickle\.loads"],
        ["3_python_pickle", "pickle"],
        ["4_python_is_object_identity_operator_left", "\d\s{1,$WILDCARD_SHORT}is\s{1,$WILDCARD_SHORT}"],
        ["4_python_is_object_identity_operator_right", "\s{1,$WILDCARD_SHORT}is\s{1,$WILDCARD_SHORT}\d"],
        ["4_python_is_object_identity_operator_general", "\sis\s"],
        ["4_python_disable_warning", "urllib3\.disable_warnings"],

        ["2_ruby_http_basic_authenticate_with", "http_basic_authenticate_with"],
        ["2_ruby_yaml", ":YAML"],
        ["2_ruby_load", ":load"],
        ["2_ruby_load_documents", ":load_documents"],
        ["2_ruby_load_stream", ":load_stream"],
        ["2_ruby_parse_documents", ":parse_documents"],
        ["2_ruby_parse_stream", ":parse_stream"],
        ["2_ruby_show_detailed_exceptions", ":show_detailed_exceptions"],
        ["2_ruby_capture", ":capture"],
        ["2_ruby_protect_from_forgery", "protect_from_forgery"],
        ["2_ruby_redirect_to", ":redirect_to"],
        ["2_ruby_verify_authenticity_token", "verify_authenticity_token"],
        ["2_ruby_validates_format_of", "validates_format_of"],
        ["3_ruby_content_tag", "content_tag"]
]
